version: '3'
services: 
    nginx:
        image: nginx:alpine
        ports:
            - '80:80'
            - '433:443'
        volumes: 
            - ../:/var/www/html/site
            - ./nginx/conf.d:/etc/nginx/conf.d:ro
            - ./nginx/logs:/var/log/nginx
            - ./nginx/html:/usr/share/nginx/html/
        links:
            - php
        restart: always
    php:
        image: martsis/php:7.3-fpm
        volumes: 
            - ../:/var/www/html/site
        environment:
            MYSQL_DATABASE: admin_base
            MYSQL_ROOT_PASSWORD: admin_base
            PGDATABASE: admin_base
            PGPASSWORD: admin_base
        links: 
            - mariadb
        restart: always
    mariadb:
        image: mariadb
        volumes: 
            - ./db/:/home/db
        environment:
            MYSQL_ROOT_PASSWORD: admin_base
            MYSQL_DATABASE: admin_base
            MYSQL_USER: admin_base
            MYSQL_PASSWORD: admin_base
        restart: always